[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch==2.8.0",
    "torchvision>=0.23.0,<0.24.0",
    "pymongo>=4.10.1,<5.0.0",
    "fastapi>=0.115.3,<0.116.0",
    "uvicorn>=0.32.0,<0.33.0",
    "python-dotenv>=1.0.1,<2.0.0",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
