env:
  NODE_ENV: prod
  AWS_REGION: us-east-1
  NEXT_PUBLIC_API_BASE: https://image-vector-search-backend.industrysolutions.prod.corp.mongodb.com

envSecrets:
   MONGO_URI: image-vector-search-secrets

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"